# Generated by Django 6.0.2 on 2026-03-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_document_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
