# Generated by Django 6.0.2 on 2026-03-16 13:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_files_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='document',
        ),
        migrations.RemoveField(
            model_name='file',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'zip'])]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.request'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
