# Generated by Django 6.0.2 on 2026-03-17 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_choice', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
