# Generated by Django 6.0.2 on 2026-03-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_userinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
