# Generated by Django 6.0.2 on 2026-04-13 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
