# Generated by Django 6.0.2 on 2026-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_request_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
