# Generated by Django 6.0.2 on 2026-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('OTHER_TYPES', 'Other Types')], default='OTHER_TYPES', max_length=12),
        ),
    ]
