# Generated by Django 6.0.2 on 2026-04-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_request_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='response_status',
            field=models.CharField(choices=[('ANSWERED', 'Answered'), ('SENT', 'Sent'), ('NOT_SENT', 'Not Sent'), ('SEEN', 'Seen')], default='NOT_SENT', max_length=12),
        ),
    ]
